data:
  requests_cpu: "0.25"
  requests_memory: "256M"
  limits_cpu: "1"
  limits_memory: "1G"
  serviceAccountName: ""
  image: ""
  cloud_sql_proxy_version: "1.20.0"
  sql_connection_string: ""

conf:
  configmap: "well-delivery-config"
  app_name: "well-delivery"
  secret_name: "well-delivery-secret"
