apiVersion: v1
kind: Secret
metadata:
  labels:
    app: "{{ .Values.conf.app_name }}"
  annotations:
    rollme: {{ randAlphaNum 5 | quote }}
  name: "{{ .Values.conf.secret_name }}"
  namespace: "{{ .Release.Namespace }}"
type: Opaque
data:
  WELL_DELIVERY_DB_PASSWORD: "{{ .Values.data.well_delivery_db_password }}"
