apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: "{{ .Values.conf.app_name }}"
  annotations:
    rollme: {{ randAlphaNum 5 | quote }}
  name: "{{ .Values.conf.configmap }}"
  namespace: "{{ .Release.Namespace }}"
data:
  WELL_DELIVERY_DB_URL: "{{ .Values.data.well_delivery_db_url }}"
  WELL_DELIVERY_DB_USERNAME: "{{ .Values.data.well_delivery_db_username }}"
  #WELL_DELIVERY_DB_PASSWORD: "{{ .Values.data.well_delivery_db_password }}"
  LEGAL_SERVICE_ENDPOINT: "{{ .Values.data.legal_service_endpoint }}"
  ENTITLEMENTS_SERVICE_ENDPOINT: "{{ .Values.data.entitlements_service_endpoint }}"
  STORAGE_SERVICE_ENDPOINT: "{{ .Values.data.storage_service_endpoint }}"
  SCHEMA_SERVICE_ENDPOINT: "{{ .Values.data.schema_service_endpoint }}"
  PARTITION_SERVICE_ENDPOINT: "{{ .Values.data.partition_service_endpoint }}"
  APP_ENTITY_STORAGE: "{{ .Values.data.app_entity_storage}}"
  LOG_LEVEL: "{{ .Values.data.log_level }}"
